# -*- coding: utf-8 -*-
"""vector.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h6W_vdSJNZC0vSZqUE0zVv02_75Aae92
"""

from sklearn.datasets import load_digits
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt

digits = load_digits()
d1 = digits.images[0]
d2 = digits.images[1]
d3 = digits.images[2]
d4 = digits.images[3]
d5 = digits.images[4]
d6 = digits.images[5]
d7 = digits.images[6]
d8 = digits.images[7]
d9 = digits.images[8]
d10 = digits.images[9]


v1 = d1.reshape(64, 1)
v2 = d2.reshape(64, 1)
v3 = d3.reshape(64, 1)
v4 = d4.reshape(64, 1)
v5 = d5.reshape(64, 1)
v6 = d6.reshape(64, 1)
v7 = d7.reshape(64, 1)
v8 = d8.reshape(64, 1)
v9 = d9.reshape(64, 1)
v10 = d10.reshape(64, 1)

plt.figure(figsize=(30, 30))
gs = gridspec.GridSpec(1, 20, height_ratios=[1],
                       width_ratios=[9, 1, 9, 1, 9, 1, 9, 1, 9, 1, 9, 1, 9, 1, 9, 1, 9, 1, 9, 1])

for i in range(10):
    plt.subplot(gs[2 * i])
    plt.imshow(eval("d" + str(i + 1)), aspect=1,
               interpolation='nearest', cmap=plt.cm.bone_r)
    plt.grid(False)
    plt.xticks([])
    plt.yticks([])
    plt.title("image {}".format(i + 1))
    plt.subplot(gs[2 * i + 1])
    plt.imshow(eval("v" + str(i + 1)), aspect=0.25,
               interpolation='nearest', cmap=plt.cm.bone_r)
    plt.grid(False)
    plt.xticks([])
    plt.yticks([])
    plt.title("vector {}".format(i + 1))
plt.tight_layout()
plt.show()

v1.T

(v1.T @ v2)[0][0]